services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    volumes:
      - airflow-meta-db:/var/lib/postgresql/data

  weather-db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${WEATHER_DB_USER}
      POSTGRES_PASSWORD: ${WEATHER_DB_PASSWORD}
      POSTGRES_DB: ${WEATHER_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - weather-db-data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  airflow-webserver:
    image: apache/airflow:2.9.0
    command: webserver
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      WEATHER_DB_HOST: ${WEATHER_DB_HOST}
      WEATHER_DB_NAME: ${WEATHER_DB_NAME}
      WEATHER_DB_USER: ${WEATHER_DB_USER}
      WEATHER_DB_PASSWORD: ${WEATHER_DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - airflow-logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy

  airflow-scheduler:
    image: apache/airflow:2.9.0
    command: scheduler
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      WEATHER_DB_HOST: ${WEATHER_DB_HOST}
      WEATHER_DB_NAME: ${WEATHER_DB_NAME}
      WEATHER_DB_USER: ${WEATHER_DB_USER}
      WEATHER_DB_PASSWORD: ${WEATHER_DB_PASSWORD}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - airflow-logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy

  airflow-init:
    image: apache/airflow:2.9.0
    command: version
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW_DB_CONN}
      AIRFLOW__CORE__FERNET_KEY: ""
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_WWW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_WWW_USER_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  airflow-meta-db:
  weather-db-data:
  airflow-logs: